### PR TITLE
Add options to config file & recursive folder traversal

### PR DESCRIPTION
**Pull request by ferares**
I really liked your script it was just what I was looking for except for some options that I needed so I forked it and added them, new features are:

- Option for specifying an output directory, if no directory is specified old behavior is preserved
- Option to include full paths to hashed files and instead of just the filenames in the manifest
- Ability to recursively explore sub folders on the given directory and preserve directory structure on the output dir

LMK of any feedback and thanks for this great and simple script!

### CODE REVIEW

**Comment by adamkiss** [comment]
@ferares Hey Fermin, I'm happy you found it to your liking, even if you had to fiddle with it a bit.

I don't personally use TypeScript and haven't had a problem with my current version for years, so I sort of considered the package to be done, but I'll review what you've done and let you know.

**Comment by ferares** [comment]
Hi @adamkiss thank you for considering merging it, I've tried to keep the original functionality intact and just add some features to it. And I can easily revert from TS to JS if you prefer in case you decide to merge the PR

**Comment by adamkiss** [comment]
Hey @ferares, finally did something with this after a long while, so I might be capable of merging this PR, if you're able/willing to revert the TS, and just add it in JS in roughly previous style, so I can double check it.

**Comment by ferares** [comment]
Hi @adamkiss, that's great, I'll get to reverting it back to js.

**Comment by ferares** [comment]
@adamkiss all done, let me know of any doubts and no worries if you don't want to merge.

**Comment by adamkiss** [comment]
@ferares i see no reason if it's only relatively simple additive code. 

I'm just also a designer, and sometimes don't work with code for months.

**Comment by adamkiss** [comment]
@ferares I've merged this, but found it too complicated and beyond the scope of what I wanted / wanted to support. I force reverted to 1.0.2, and if you want exclusion / directory recursion, you'll have to maintain your own fork/library. Sorry for wasting your time with un-Typescripting your code.

Have a good day.

**Comment by ferares** [comment]
@adamkiss no worries! thanks for looking into it

**Pull request merged**
